name: dota2_responser
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.16.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/
    - assets/Abaddon/
    - assets/Acolyte_of_the_Lost_Arts/
    - assets/Aghanim's_Labyrinth Announcer/
    - assets/Alchemist/
    - assets/Ancient_Apparition/
    - assets/Announcer_responses/
    - assets/Announcer:_Death_Prophet/
    - assets/Announcer:_Dr._Kleiner/
    - assets/Announcer:_Tusk/
    - assets/Anti-Mage/
    - assets/Arc_Warden/
    - assets/Axe_Announcer_Pack/
    - assets/Axe_Unleashed/
    - assets/Axe/
    - assets/Bane/
    - assets/Bastion_Announcer_Pack/
    - assets/Batrider/
    - assets/Beastmaster/
    - assets/Bloodseeker/
    - assets/Bounty_Hunter/
    - assets/Brewmaster/
    - assets/Bristleback_Announcer_Pack/
    - assets/Bristleback/
    - assets/Broodmother/
    - assets/Call_of_the_Bladeform_Legacy/
    - assets/Centaur_Warrunner/
    - assets/Chaos_Knight/
    - assets/Chen/
    - assets/Clinkz/
    - assets/Clockwerk_Announcer_Pack/
    - assets/Clockwerk/
    - assets/Compass_of_the_Rising_Gale_Bundle/
    - assets/Crystal_Maiden_Announcer_Pack/
    - assets/Crystal_Maiden/
    - assets/Dark_Seer/
    - assets/Dark_Willow_Announcer_Pack/
    - assets/Dark_Willow/
    - assets/Darkest_Dungeon_Announcer_Pack_(ft._Wayne_June)/
    - assets/Dazzle/
    - assets/Death_Prophet/
    - assets/Defense_Grid_Announcer_Pack/
    - assets/Deus_Ex_Announcer_Pack/
    - assets/Disruptor/
    - assets/Doom/
    - assets/Dragon_Knight/
    - assets/Drow_Ranger/
    - assets/Earth_Spirit/
    - assets/Earthshaker/
    - assets/Elder_Titan/
    - assets/Ember_Spirit/
    - assets/Enchantress/
    - assets/Enigma/
    - assets/Faceless_Void/
    - assets/Fallout_4_Announcer_Pack/
    - assets/Feast_of_Abscession/
    - assets/Grimstroke/
    - assets/Gyrocopter/
    - assets/Huskar/
    - assets/Invoker/
    - assets/Io/
    - assets/Jakiro/
    - assets/Juggernaut_Announcer_Pack/
    - assets/Juggernaut/
    - assets/Keeper_of_the_Light/
    - assets/Kunkka_&_Tidehunter_Announcer_Pack/
    - assets/Kunkka/
    - assets/Legion_Commander/
    - assets/Leshrac/
    - assets/Lich/
    - assets/Lifestealer/
    - assets/Lina_Announcer_Pack/
    - assets/Lina/
    - assets/Lion/
    - assets/Lone_Druid/
    - assets/Luna/
    - assets/Lycan/
    - assets/Magnus/
    - assets/Mars/
    - assets/Medusa/
    - assets/Meepo_Announcer_Pack/
    - assets/Meepo/
    - assets/Mega-Kills:_Gabe_Newell/
    - assets/Mercurial's_Call/
    - assets/Mirana/
    - assets/Monkey_King_Announcer_Pack/
    - assets/Monkey_King/
    - assets/Morphling/
    - assets/Naga_Siren/
    - assets/Nature's_Prophet_Announcer_Pack/
    - assets/Nature's_Prophet/
    - assets/Necrophos/
    - assets/Night_Stalker/
    - assets/Nyx_Assassin/
    - assets/Ogre_Magi/
    - assets/Omniknight/
    - assets/Oracle/
    - assets/Outworld_Devourer/
    - assets/Pangolier/
    - assets/Phantom_Assassin/
    - assets/Phantom_Lancer/
    - assets/Phoenix/
    - assets/Planetfall/
    - assets/Portal_Pack/
    - assets/Puck/
    - assets/Pudge/
    - assets/Pugna/
    - assets/Pyrion_Flax_Announcer_Pack/
    - assets/Queen_of_Pain/
    - assets/Razor/
    - assets/Rick_and_Morty_Announcer_Pack/
    - assets/Riki/
    - assets/Rubick/
    - assets/Sand_King/
    - assets/Shadow_Demon/
    - assets/Shadow_Fiend/
    - assets/Shadow_Shaman/
    - assets/Shopkeeper_responses/
    - assets/Silencer/
    - assets/Skeleton_King/
    - assets/Slardar/
    - assets/Skywrath_Mage/
    - assets/Slardar/
    - assets/Slark/
    - assets/Snapfire/
    - assets/Sniper/
    - assets/Spectre/
    - assets/Spirit_Breaker/
    - assets/Storm_Spirit_Announcer_Pack/
    - assets/Storm_Spirit/
    - assets/Sven/
    - assets/Techies'_Bombastic_Box/
    - assets/Techies/
    - assets/Templar_Assassin/
    - assets/Terrorblade/
    - assets/The_Disciple's_Path/
    - assets/The_Eminence_of_Ristul_Bundle/
    - assets/The_One_True_King_Bundle/
    - assets/The_Pirate_Cap'n_Announcer_Pack/
    - assets/The_Stanley_Parable_Announcer_Pack/
    - assets/The_Toy_Butcher/
    - assets/Tidehunter/
    - assets/Timbersaw/
    - assets/Tinker/
    - assets/Tiny/
    - assets/Treant_Protector/
    - assets/Trine_Announcer_Pack/
    - assets/Tiny/
    - assets/Treant_Protector/
    - assets/Trine_Announcer_Pack/
    - assets/Troll_Warlord/
    - assets/Tusk/
    - assets/Underlord/
    - assets/Undying/
    - assets/Ursa/
    - assets/Vengeful_Spirit/
    - assets/Venomancer/
    - assets/Viper/
    - assets/Visage/
    - assets/Voice_of_Flockheart's_Gamble/
    - assets/Voice_of_The_International_Announcer_Pack/
    - assets/Voice_of_the_Magus_Cypher/
    - assets/Void_Spirit/
    - assets/Warlock_Golem/
    - assets/Warlock/
    - assets/Weaver/
    - assets/Windranger/
    - assets/Winter_Wyvern/
    - assets/Witch_Doctor/
    - assets/Wraith_King/
    - assets/Zeus/
